services:
  - type: web
    name: plataforma-arirang
    dockerfilePath: Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: homolog
      - key: SERVER_PORT
        value: 10000
      - key: SERVER_ADDRESS
        value: 0.0.0.0
